[features]
seeds = false
[programs.devnet]
solana_raffles = "bhEzYEpMDxas9VV85s85KsnzY4nhCvJaRXW23hN7Sty"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/axiom/Desktop/Workspace/Axiom/BLOCKCHAIN/Learning/SeCbhUgwfifKUVc3Ut5Z7hRCRMsPyFr1Z4hyargXYYv.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
